### ISSUE TITLE
Make Sigin up require username, allow login with username

### ISSUE THREAD

**Issue by HackerMasterEango** [HackerMasterEango/eangowen.moe#1]
Currently the apps authentication is just email and password.

1. Make sign up require a username.
2. Allow login to either supply a username or password

the main file to edit will be in /src/actions/loginUser.ts

those are server-side actions. But also minor ui updates too on the login/sign up forms.

BONUS: make user type password twice for signup and validate on frontend.

DATABASE - 
query editor here - https://supabase.com/dashboard/project/aqcljqoengodgartkjex/sql/new
can manually delete your user from the auth.users table to test/retest flow works.

select * from auth.users;

MY GUESS
is for username login you will need to make a select statement on the auth table to the the email for the username, and then
use that emial/password for the login. Make sure we cant have duplicated usernames though if that is the approach.

**Comment by Lolergags** [comment]
Added the username signup + login check for username or email. Haven't tested xd.
